spring:
  application:
    name: ms-products-svc
  profiles:
    active: default
  datasource:
    url: jdbc:mariadb://dbd.lomosrv.com/sbms_products_ms
    username: devlomo
    password: P@lomo53
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    
server:
  port: 8001

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://eurekasrv.sbms.com:8761/eureka